### PR TITLE
bank: validation for username and password

### LINKED ISSUE #74: bank: protect bad user registrations with proper validation
We should implement username and password validation on the server.
Given only valid values for username and password registration or login requests should proceed.

Tasks
- implement validation for the values of username and password.

### PR DESCRIPTION
**Pull request by gadjevb**
Added a basic validation for username and password. For a username to be valid, it must contain a-zA-Z0-9 with length between 6 - 50 character. For a password to be valid, it must contain a-zA-Z0-9 with length between 6 - 18 characters.

Fixes #74

### CODE REVIEW

**Comment by gadjevb** [comment]
I've was using the html page requirements for the length. Don't know if I should have changed them. For now I'm testing if the input values are too short in the tests, should I add tests if they are too long?

**Comment by mgenov** [comment]
Looks duplicated and with a little bit different design with the work that was done in #105

**Comment by mgenov** [comment]
cc @martinmilev

**Comment by gadjevb** [comment]
If I'm not mistaken, I was assigned to #74

**Comment by mgenov** [comment]
It's already partially added in #105, so I'm closing the issue.

**Pull request closed without merging**
